### PR TITLE
Add CORS middleware, config for accept fetching data from frontend (guweb)

### PR DESCRIPTION
**Pull request by Varkaria**
for fixing `Access to XMLHttpRequest at 'https://domain/endpoint' from origin 'frontend_domain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

### CODE REVIEW

**Comment by tsunyoku** [comment]
we already have some unpushed commits relating to cors and other middlewares, but i’ll keep this open and unmerged for now just in case.

**Comment by cmyui** [comment]
Oh nice! Thanks I'll merge this soon with the other PRs.

**Comment by cmyui** [comment]
few things that came to mind,
1. are the `api.` and `osu.` subdomain origins required for CORS as well?
2. is :3000 for the frontend? i believe guweb is configured to run on 8000
3. we may be able to remove the config option by doing it dynamically in python with `app.settings.DOMAIN`

**Comment by cmyui** [comment]
not sure about this one, don't think we should be hacking around things with cors, there may be a better fix on FE side here?

**Pull request closed without merging**
